# Generated by Django 5.1.1 on 2024-11-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(max_length=30)),
                ('apellidos', models.TextField(max_length=30)),
                ('rut', models.TextField(max_length=12, unique=True)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('telefono', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.TextField(unique=True)),
                ('contrasena', models.TextField()),
                ('estado', models.IntegerField(default=1)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoOmnicell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('metodouso', models.TextField(blank=True, max_length=100, null=True)),
                ('contraindicaciones', models.TextField(blank=True, max_length=100, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('fechavisita', models.DateTimeField()),
                ('presionart', models.TextField(blank=True, max_length=10, null=True)),
                ('frecuenciacard', models.TextField(blank=True, max_length=10, null=True)),
                ('saturometria', models.TextField(blank=True, max_length=10, null=True)),
                ('temperatura', models.TextField(blank=True, max_length=10, null=True)),
                ('hemoglucotest', models.TextField(blank=True, max_length=10, null=True)),
                ('motivovisita', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.paciente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.trabajador')),
            ],
        ),
    ]
