# Generated by Django 5.1.1 on 2024-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=15)),
                ('rut', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=15)),
                ('segNom', models.CharField(max_length=15)),
                ('apePaterno', models.CharField(max_length=15)),
                ('apeMaterno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
