# Generated by Django 5.1.1 on 2024-11-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_insumos_remove_inventario_contraindicaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioomnicell',
            name='trabajador',
        ),
    ]
