# Generated by Django 5.1.1 on 2024-11-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_remove_inventarioomnicell_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoomnicell',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.insumos'),
        ),
    ]
