# Generated by Django 5.1.1 on 2024-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_alter_pedidoomnicell_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoomnicell',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
