# Generated by Django 5.1.1 on 2024-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_pedidoomnicell_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
