# Generated by Django 5.1.1 on 2024-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_alter_trabajador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoomnicell',
            name='fecha',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
