# Generated by Django 5.1.1 on 2024-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_pedidoomnicell_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='condiciones',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
